import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import ReactLenis from "@/app/_components/react-lenis";

const paragraph = localFont({
  src: [
    {
      path: "../../public/fonts/fonnts.com-Paralucent_Medium.otf",
      weight: "500",
    },
    {
      path: "../../public/fonts/fonnts.com-Paralucent_Light.otf",
      weight: "300",
    },
    {
      path: "../../public/fonts/fonnts.com-Paralucent_Demi_Bold.otf",
      weight: "800",
    },
  ],
  variable: "--heading",
  display: "swap",
  // weight: "800",
});

const heading = localFont({
  src: [
    {
      path: "../../public/fonts/fonnts.com-Paralucent_Medium.otf",
      weight: "500",
    },
    {
      path: "../../public/fonts/fonnts.com-Paralucent_Light.otf",
      weight: "300",
    },
    {
      path: "../../public/fonts/fonnts.com-Paralucent_Demi_Bold.otf",
      weight: "800",
    },
  ],
  variable: "--paragraph",
  display: "swap",
  // weight: "800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${heading.variable} ${paragraph.variable}`,
          "antialiased grainy font-sans min-h-screen w-screen relative overflow-x-hidden"
        )}
      >
        {children}
      </body>
    </html>
  );
}
